--- # jekyll's config file
title: "Cadavre Exquis' Site"
description: "just a generic site ..."
jsrelease: 1.4.4
tag: z3NDG9cEMmiqrsb3Rr5ptQbG6DvW9dUUUgUB
netname: cadavre-exquis-b5d9571
badgename: de6237a3-8ef2-456b-929f-3cb2eff2ca8c
